### ISSUE TITLE
Unsecure documentation

### ISSUE THREAD

**Issue by TheBoxyBear** [dotmenu/dotmenu#5]
The documentation website [https://dotmenu.natesworks.com](https://dotmenu.natesworks.com) along with the parent domain are not configured to use Https, making it harder to access and less credible.

**Comment by natesworks** [comment]
Hi! For me it seems to use https by default but that may not be the case on all browsers I will enforce https right now, thanks for pointing that out!

**Comment by natesworks** [comment]
Should be fixed now!

**Comment by natesworks** [comment]
Fixed
